/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
export type AllergiesCreatedAt = string | null;

export interface Allergies {
    id: number;
    createdAt?: AllergiesCreatedAt;
    substance: string;
    reaction: string;
    severity: string;
    notedAt: string;
    patientId: number;
}

export type DiagnosesResponseCreatedAt = string | null;

export type DiagnosesResponseResolved = string | null;

export interface DiagnosesResponse {
    id: number;
    createdAt?: DiagnosesResponseCreatedAt;
    code: string;
    description: string;
    type: DiagnosisTypeEnum;
    onset: string;
    resolved?: DiagnosesResponseResolved;
    patientId: number;
    encounterId: number;
    authorId: number;
    author: UserRead;
}

export type DiagnosisTypeEnum =
    (typeof DiagnosisTypeEnum)[keyof typeof DiagnosisTypeEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DiagnosisTypeEnum = {
    PRIMARY: 'PRIMARY',
    SECONDARY: 'SECONDARY',
    DIFFERENTIAL: 'DIFFERENTIAL',
} as const;

export type EncounterDetailResponseCreatedAt = string | null;

export interface EncounterDetailResponse {
    id: number;
    createdAt?: EncounterDetailResponseCreatedAt;
    type: EncounterTypeEnum;
    status: EncounterStatusEnum;
    start: string;
    end: string;
    reason: string;
    patientId: number;
    location: string;
    createdById: number;
    patient: PatientDetailResponse;
    createdBy: UserRead;
    medicalRecords?: MedicalRecordsResponse[];
    diagnoses?: DiagnosesResponse[];
    medicationOrders?: string[];
}

export type EncounterListResponseCreatedAt = string | null;

export interface EncounterListResponse {
    id: number;
    createdAt?: EncounterListResponseCreatedAt;
    type: EncounterTypeEnum;
    status: EncounterStatusEnum;
    start: string;
    end: string;
    reason: string;
    patientId: number;
    patient: PatientRead;
    createdBy: UserRead;
}

export type EncounterResponseCreatedAt = string | null;

export interface EncounterResponse {
    id: number;
    createdAt?: EncounterResponseCreatedAt;
    type: EncounterTypeEnum;
    status: EncounterStatusEnum;
    start: string;
    end: string;
    reason: string;
    patientId: number;
    location: string;
    createdById: number;
}

export type EncounterStatusEnum =
    (typeof EncounterStatusEnum)[keyof typeof EncounterStatusEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EncounterStatusEnum = {
    PLANNED: 'PLANNED',
    IN_PROGRESS: 'IN_PROGRESS',
    COMPLETED: 'COMPLETED',
    CANCELLED: 'CANCELLED',
} as const;

export type EncounterTypeEnum =
    (typeof EncounterTypeEnum)[keyof typeof EncounterTypeEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EncounterTypeEnum = {
    INPATIENT: 'INPATIENT',
    OUTPATIENT: 'OUTPATIENT',
    EMERGENCY: 'EMERGENCY',
    TELEHEALTH: 'TELEHEALTH',
    OTHER: 'OTHER',
} as const;

export type GenderEnum = (typeof GenderEnum)[keyof typeof GenderEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GenderEnum = {
    MALE: 'MALE',
    FEMALE: 'FEMALE',
    MX: 'MX',
    OTHER: 'OTHER',
    UNKNOWN: 'UNKNOWN',
} as const;

export interface HTTPValidationError {
    detail?: ValidationError[];
}

export type InsurancePoliciesCreatedAt = string | null;

export type InsurancePoliciesEndDate = string | null;

export interface InsurancePolicies {
    id: number;
    createdAt?: InsurancePoliciesCreatedAt;
    policyNumber: string;
    status: InsuranceStatusEnum;
    startDate: string;
    endDate?: InsurancePoliciesEndDate;
    patientId: number;
    insurerId: number;
    insurer: Insurer;
}

export type InsuranceStatusEnum =
    (typeof InsuranceStatusEnum)[keyof typeof InsuranceStatusEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const InsuranceStatusEnum = {
    ACTIVE: 'ACTIVE',
    ENDED: 'ENDED',
    PENDING: 'PENDING',
} as const;

export type InsurerCreatedAt = string | null;

export type InsurerAddress = string | null;

export interface Insurer {
    id: number;
    createdAt?: InsurerCreatedAt;
    name: string;
    code: string;
    phone: string;
    email: string;
    website: string;
    address?: InsurerAddress;
}

export type MedicalRecordTypeEnum =
    (typeof MedicalRecordTypeEnum)[keyof typeof MedicalRecordTypeEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MedicalRecordTypeEnum = {
    NOTE: 'NOTE',
    CONSULTATION: 'CONSULTATION',
    PROCEDURE_SUMMARY: 'PROCEDURE_SUMMARY',
    DISCHARGE_SUMMARY: 'DISCHARGE_SUMMARY',
    REPORT: 'REPORT',
    CHAT_SUMMARY: 'CHAT_SUMMARY',
} as const;

export type MedicalRecordsResponseCreatedAt = string | null;

export interface MedicalRecordsResponse {
    id: number;
    createdAt?: MedicalRecordsResponseCreatedAt;
    type: MedicalRecordTypeEnum;
    title: string;
    content: string;
    patientId: number;
    encounterId: number;
    authorId: number;
    author: UserRead;
}

export interface PaginatedEncounterResponse {
    encounters: EncounterListResponse[];
    pagination: PaginationResponse;
}

export interface PaginatedPatientResponse {
    patients: PatientDetailResponse[];
    pagination: PaginationResponse;
}

export interface PaginationResponse {
    page: number;
    limit: number;
    total: number;
    totalPages: number;
}

export type PatientDetailResponseCreatedAt = string | null;

export type PatientDetailResponseRole = UserRoleEnum | null;

export type PatientDetailResponseAddressLine2 = string | null;

export interface PatientDetailResponse {
    id: number;
    createdAt?: PatientDetailResponseCreatedAt;
    firstName: string;
    lastName: string;
    email: string;
    role?: PatientDetailResponseRole;
    hospitalNumber: string;
    dateOfBirth: string;
    sex: GenderEnum;
    phone: string;
    addressLine1: string;
    addressLine2?: PatientDetailResponseAddressLine2;
    city: string;
    postalCode: string;
    status: PatientStatusEnum;
    updatedAt: string;
    createdById: number;
    createdBy: User;
    encounters: EncounterResponse[];
    diagnoses: DiagnosesResponse[];
    allergies: Allergies[];
    insurancePolicies: InsurancePolicies[];
}

export type PatientReadCreatedAt = string | null;

export interface PatientRead {
    id: number;
    createdAt?: PatientReadCreatedAt;
    hospitalNumber: string;
    firstName: string;
    lastName: string;
}

export type PatientStatusEnum =
    (typeof PatientStatusEnum)[keyof typeof PatientStatusEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PatientStatusEnum = {
    ACTIVE: 'ACTIVE',
    DISCHARGED: 'DISCHARGED',
    DECEASED: 'DECEASED',
} as const;

export interface TokenResponse {
    message: string;
    accessToken: string;
    refreshToken: string;
    expiresIn: string;
    user: User;
}

export type UserCreatedAt = string | null;

export type UserRole = UserRoleEnum | null;

export interface User {
    id: number;
    createdAt?: UserCreatedAt;
    firstName: string;
    lastName: string;
    email: string;
    role?: UserRole;
}

export type UserReadCreatedAt = string | null;

export interface UserRead {
    id: number;
    createdAt?: UserReadCreatedAt;
    firstName: string;
    lastName: string;
}

export type UserRoleEnum = (typeof UserRoleEnum)[keyof typeof UserRoleEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserRoleEnum = {
    NURSE: 'NURSE',
    DOCTOR: 'DOCTOR',
    ASSISTANT: 'ASSISTANT',
    ADMIN: 'ADMIN',
} as const;

export type ValidationErrorLocItem = string | number;

export interface ValidationError {
    loc: ValidationErrorLocItem[];
    msg: string;
    type: string;
}

export type CreateTokenAuthLoginPostParams = {
    email: string;
    password: string;
};

export type RegisterUserAuthRegisterPostParams = {
    id: number;
    createdAt?: string | null;
    firstName: string;
    lastName: string;
    email: string;
    role?: UserRoleEnum | null;
    password: string;
};

export type GetEncountersEncountersGetParams = {
    page?: number | null;
    limit?: number | null;
    encounter_id?: number | null;
    encounter_status?: EncounterStatusEnum | null;
    encounter_type?: EncounterTypeEnum | null;
};

export type CreateEncounterEncountersPostParams = {
    id: number;
    createdAt?: string | null;
    type: EncounterTypeEnum;
    status: EncounterStatusEnum;
    start: string;
    end: string;
    reason: string;
    patientId: number;
    location: string;
    createdById: number;
};

export type UpdateEncounterEncountersEncounterIdPutParams = {
    id: number;
    createdAt?: string | null;
    type: EncounterTypeEnum;
    status: EncounterStatusEnum;
    start: string;
    end: string;
    reason: string;
    patientId: number;
    location: string;
    createdById: number;
};

export type GetPatientsPatientGetParams = {
    limit?: number | null;
    offset?: number | null;
    patient_status?: PatientStatusEnum | null;
    search?: string | null;
};

export type CreatePatientPatientPostParams = {
    id: number;
    createdAt?: string | null;
    firstName: string;
    lastName: string;
    email: string;
    role?: UserRoleEnum | null;
    hospitalNumber: string;
    dateOfBirth: string;
    sex: GenderEnum;
    phone: string;
    addressLine1: string;
    addressLine2?: string | null;
    city: string;
    postalCode: string;
    status: PatientStatusEnum;
    updatedAt: string;
    createdById: number;
};

export type UpdatePatientPatientPatientIdPutParams = {
    id: number;
    createdAt?: string | null;
    firstName: string;
    lastName: string;
    email: string;
    role?: UserRoleEnum | null;
    hospitalNumber: string;
    dateOfBirth: string;
    sex: GenderEnum;
    phone: string;
    addressLine1: string;
    addressLine2?: string | null;
    city: string;
    postalCode: string;
    status: PatientStatusEnum;
    updatedAt: string;
    createdById: number;
};

export type RootGet200 = { [key: string]: string };
