// seed.ts
// Seed localStorage with dummy data for patients, lab-results, and conversations

export function seedLocalStorage() {
    // Only seed if empty
    if (!localStorage.getItem('patients')) {
        localStorage.setItem(
            'patients',
            JSON.stringify([
                {
                    id: 'p1',
                    name: 'Jan Jansen',
                    dateOfBirth: '1980-01-01',
                    gender: 'M',
                    email: 'jan.jansen@example.com',
                    phone: '0612345678',
                    condition: 'diabetes',
                    status: 'Stabiel',
                    lastUpdated: new Date(Date.now() - Math.random() * 365 * 24 * 60 * 60 * 1000).toISOString(),
                },
                {
                    id: 'p2',
                    name: 'Pietje Puk',
                    dateOfBirth: '1992-05-12',
                    gender: 'M',
                    email: 'pietje.puk@example.com',
                    phone: '0687654321',
                    condition: 'diabetes',
                    status: 'Monitoren',
                    lastUpdated: new Date(Date.now() - Math.random() * 365 * 24 * 60 * 60 * 1000).toISOString(),
                },
                {
                    id: 'p3',
                    name: 'Kees Koks',
                    dateOfBirth: '1975-11-25',
                    gender: 'M',
                    email: 'kees.koks@example.com',
                    phone: '0678901234',
                    condition: 'diabetes',
                    status: 'Stabiel',
                    lastUpdated: new Date(Date.now() - Math.random() * 365 * 24 * 60 * 60 * 1000).toISOString(),
                },
                {
                    id: 'p4',
                    name: 'Ellen Evers',
                    dateOfBirth: '1995-07-10',
                    gender: 'V',
                    email: 'ellen.evers@example.com',
                    phone: '0632141516',
                    condition: 'diabetes',
                    status: 'Stabiel',
                    lastUpdated: new Date(Date.now() - Math.random() * 365 * 24 * 60 * 60 * 1000).toISOString(),
                },
                {
                    id: 'p5',
                    name: 'Frisje Franssen',
                    dateOfBirth: '1987-03-15',
                    gender: 'V',
                    email: 'frisje.franssen@example.com',
                    phone: '0623456789',
                    condition: 'diabetes',
                    status: 'Kritiek',
                    lastUpdated: new Date(Date.now() - Math.random() * 365 * 24 * 60 * 60 * 1000).toISOString(),
                },
                {
                    id: 'p6',
                    name: 'Pieter Pieters',
                    dateOfBirth: '1991-02-28',
                    gender: 'M',
                    email: 'pieter.pieters@example.com',
                    phone: '0654321098',
                    condition: 'diabetes',
                    status: 'Stabiel',
                    lastUpdated: new Date(Date.now() - Math.random() * 365 * 24 * 60 * 60 * 1000).toISOString(),
                },
                {
                    id: 'p7',
                    name: 'Janneke Janse',
                    dateOfBirth: '1984-09-22',
                    gender: 'V',
                    email: 'janneke.janse@example.com',
                    phone: '0611223344',
                    condition: 'diabetes',
                    status: 'Monitoren',
                    lastUpdated: new Date(Date.now() - Math.random() * 365 * 24 * 60 * 60 * 1000).toISOString(),
                },
                {
                    id: 'p8',
                    name: 'Joris Jansen',
                    dateOfBirth: '1988-05-30',
                    gender: 'M',
                    email: 'joris.jansen@example.com',
                    phone: '0677665544',
                    condition: 'diabetes',
                    status: 'Stabiel',
                    lastUpdated: new Date(Date.now() - Math.random() * 365 * 24 * 60 * 60 * 1000).toISOString(),
                },
                {
                    id: 'p9',
                    name: 'Lucie Lucas',
                    dateOfBirth: '1993-12-08',
                    gender: 'V',
                    email: 'lucie.lucas@example.com',
                    phone: '0644556677',
                    condition: 'diabetes',
                    status: 'Stabiel',
                    lastUpdated: new Date(Date.now() - Math.random() * 365 * 24 * 60 * 60 * 1000).toISOString(),
                },
                {
                    id: 'p10',
                    name: 'Karel Kruiper',
                    dateOfBirth: '1982-01-13',
                    gender: 'M',
                    email: 'karel.kruiper@example.com',
                    phone: '0633221100',
                    condition: 'diabetes',
                    status: 'Stabiel',
                    lastUpdated: new Date(Date.now() - Math.random() * 365 * 24 * 60 * 60 * 1000).toISOString(),
                },
            ]),
        );
    }
    if (!localStorage.getItem('labResults')) {
        localStorage.setItem(
            'labResults',
            JSON.stringify([
                {
                    id: 'l1',
                    type: 'Glucose',
                    value: 5.6,
                    unit: 'mmol/L',
                    minValue: 4,
                    maxValue: 7,
                    patient: { id: 'p1', name: 'Jan Jansen' },
                    timestamp: '2026-01-01T10:00:00Z',
                },
                {
                    id: 'l2',
                    type: 'Glucose',
                    value: 5.8,
                    unit: 'mmol/L',
                    minValue: 4,
                    maxValue: 7,
                    patient: { id: 'p2', name: 'Pietje Puk' },
                    timestamp: '2026-01-02T10:00:00Z',
                },
                {
                    id: 'l3',
                    type: 'Glucose',
                    value: 5.4,
                    unit: 'mmol/L',
                    minValue: 4,
                    maxValue: 7,
                    patient: { id: 'p1', name: 'Jan Jansen' },
                    timestamp: '2026-01-03T10:00:00Z',
                },
                {
                    id: 'l4',
                    type: 'Glucose',
                    value: 5.9,
                    unit: 'mmol/L',
                    minValue: 4,
                    maxValue: 7,
                    patient: { id: 'p1', name: 'Jan Jansen' },
                    timestamp: '2026-01-04T10:00:00Z',
                },
                {
                    id: 'l5',
                    type: 'Glucose',
                    value: 5.7,
                    unit: 'mmol/L',
                    minValue: 4,
                    maxValue: 7,
                    patient: { id: 'p1', name: 'Jan Jansen' },
                    timestamp: '2026-01-05T10:00:00Z',
                },
                {
                    id: 'l6',
                    type: 'Glucose',
                    value: 5.3,
                    unit: 'mmol/L',
                    minValue: 4,
                    maxValue: 7,
                    patient: { id: 'p2', name: 'Pietje Puk' },
                    timestamp: '2026-01-03T10:00:00Z',
                },
                {
                    id: 'l7',
                    type: 'Glucose',
                    value: 5,
                    unit: 'mmol/L',
                    minValue: 4,
                    maxValue: 7,
                    patient: { id: 'p2', name: 'Pietje Puk' },
                    timestamp: '2026-01-04T10:00:00Z',
                },
                {
                    id: 'l8',
                    type: 'Glucose',
                    value: 5.2,
                    unit: 'mmol/L',
                    minValue: 4,
                    maxValue: 7,
                    patient: { id: 'p2', name: 'Pietje Puk' },
                    timestamp: '2026-01-05T10:00:00Z',
                },
                {
                    id: 'l9',
                    type: 'Glucose',
                    value: 5.5,
                    unit: 'mmol/L',
                    minValue: 4,
                    maxValue: 7,
                    patient: { id: 'p3', name: 'Kees Koks' },
                    timestamp: '2026-01-03T10:00:00Z',
                },
                {
                    id: 'l10',
                    type: 'Glucose',
                    value: 5.1,
                    unit: 'mmol/L',
                    minValue: 4,
                    maxValue: 7,
                    patient: { id: 'p3', name: 'Kees Koks' },
                    timestamp: '2026-01-04T10:00:00Z',
                },
            ]),
        );
    }
    if (!localStorage.getItem('conversations')) {
        localStorage.setItem(
            'conversations',
            JSON.stringify([
                {
                    id: 'c1',
                    message: 'Welkom bij het EPD!',
                    to: { id: 'p1', name: 'Jan Jansen' },
                    from: { id: 'admin', name: 'Admin', email: 'admin@example.com' },
                    timestamp: '2026-01-01T10:00:00Z',
                },
                {
                    id: 'c2',
                    message: 'Heb je nog vragen over je labresultaten?',
                    to: { id: 'p1', name: 'Jan Jansen' },
                    from: { id: 'admin', name: 'Admin', email: 'admin@example.com' },
                    timestamp: '2026-01-02T14:30:00Z',
                },
                {
                    id: 'c3',
                    message: 'Blijf in contact voor verdere update!',
                    to: { id: 'p1', name: 'Jan Jansen' },
                    from: { id: 'admin', name: 'Admin', email: 'admin@example.com' },
                    timestamp: '2026-01-03T15:45:00Z',
                },
                {
                    id: 'c4',
                    message: 'Bedankt voor het gebruik van het EPD!',
                    to: { id: 'p1', name: 'Jan Jansen' },
                    from: { id: 'admin', name: 'Admin', email: 'admin@example.com' },
                    timestamp: '2026-01-04T17:00:00Z',
                },
                {
                    id: 'c5',
                    message: 'Welkom bij het EPD!',
                    to: { id: 'p2', name: 'Pietje Puk' },
                    from: { id: 'admin', name: 'Admin', email: 'admin@example.com' },
                    timestamp: '2026-01-02T14:30:00Z',
                },
                {
                    id: 'c6',
                    message: 'Heb je nog vragen over je labresultaten?',
                    to: { id: 'p2', name: 'Pietje Puk' },
                    from: { id: 'admin', name: 'Admin', email: 'admin@example.com' },
                    timestamp: '2026-01-03T15:45:00Z',
                },
                {
                    id: 'c7',
                    message: 'Blijf in contact voor verdere update!',
                    to: { id: 'p2', name: 'Pietje Puk' },
                    from: { id: 'admin', name: 'Admin', email: 'admin@example.com' },
                    timestamp: '2026-01-04T17:00:00Z',
                },
                {
                    id: 'c8',
                    message: 'Bedankt voor het gebruik van het EPD!',
                    to: { id: 'p2', name: 'Pietje Puk' },
                    from: { id: 'admin', name: 'Admin', email: 'admin@example.com' },
                    timestamp: '2026-01-05T19:15:00Z',
                },
                {
                    id: 'c9',
                    message: 'Welkom bij het EPD!',
                    to: { id: 'p3', name: 'Kees Koks' },
                    from: { id: 'admin', name: 'Admin', email: 'admin@example.com' },
                    timestamp: '2026-01-02T14:30:00Z',
                },
                {
                    id: 'c10',
                    message: 'Heb je nog vragen over je labresultaten?',
                    to: { id: 'p3', name: 'Kees Koks' },
                    from: { id: 'admin', name: 'Admin', email: 'admin@example.com' },
                    timestamp: '2026-01-03T15:45:00Z',
                },
                {
                    id: 'c11',
                    message: 'Blijf in contact voor verdere update!',
                    to: { id: 'p3', name: 'Kees Koks' },
                    from: { id: 'admin', name: 'Admin', email: 'admin@example.com' },
                    timestamp: '2026-01-04T17:00:00Z',
                },
                {
                    id: 'c12',
                    message: 'Bedankt voor het gebruik van het EPD!',
                    to: { id: 'p3', name: 'Kees Koks' },
                    from: { id: 'admin', name: 'Admin', email: 'admin@example.com' },
                    timestamp: '2026-01-05T19:15:00Z',
                },
            ]),
        );
    }
}
