name: CI Frontend
description: Runs Continuous Integration for the frontend
runs:
    using: composite
    steps:
        - name: Setup Node.js
          uses: actions/setup-node@v6
          with:
            node-version-file: .tool-versions
            cache: npm
            cache-dependency-path: frontend/package-lock.json

        - name: Install dependencies
          shell: bash
          working-directory: frontend
          run: npm ci

        - name: Check formatting
          shell: bash
          working-directory: frontend
          run: npm run format:check

        - name: Check linting
          shell: bash
          working-directory: frontend
          run: npm run lint

        - name: Compile app
          shell: bash
          working-directory: frontend
          run: npm run build

        - name: Run tests
          shell: bash
          working-directory: frontend
          run: |
            npx playwright install chromium
            npm run test